/* Generated by Pyrex 0.9.8.5 on Mon Dec 14 17:08:01 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "python-compat.h"
#include "stdlib.h"
#include "string.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static char __pyx_mdoc[] = "Pyrex extensions to btree node parsing.";

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from bzrlib._btree_serializer_pyx */


/* Declarations from implementation of bzrlib._btree_serializer_pyx */

struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser {
  PyObject_HEAD
  struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *__pyx_vtab;
  PyObject *bytes;
  int key_length;
  int ref_list_length;
  PyObject *keys;
  char *_cur_str;
  char *_end_str;
  char *_start;
  int _header_found;
};


struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser {
  PyObject *(*extract_key)(struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *,char *);
  int (*process_line)(struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *);
};
static struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *__pyx_vtabptr_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser;

static PyTypeObject *__pyx_ptype_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser = 0;
static void *__pyx_f_6bzrlib_21_btree_serializer_pyx__my_memrchr(void *,int,size_t); /*proto*/
static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_safe_string_from_size(char *,Py_ssize_t); /*proto*/
static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_safe_interned_string_from_size(char *,Py_ssize_t); /*proto*/

static char __pyx_k1[] = "tried to create a string with an invalid size: %d @0x%x";
static char __pyx_k2[] = "invalid key, wanted segment from ";
static char __pyx_k3[] = "last < self._start";
static char __pyx_k4[] = "type=leaf";
static char __pyx_k5[] = "Node did not start with \"type=leaf\": %r";
static char __pyx_k6[] = "Failed to find the value area";
static char __pyx_k7[] = "invalid key, loop_counter != self.ref_list_length";
static char __pyx_k8[] = "unexpected reference data present";
static char __pyx_k9[] = "self.bytes is not a string.";
static char __pyx_k10[] = "parse";
static char __pyx_k11[] = "We expected a tuple() for node not: %s";
static char __pyx_k12[] = "With ref_lists, we expected 4 entries not: %s";
static char __pyx_k13[] = "Without ref_lists, we need at least 3 entries not: %s";
static char __pyx_k14[] = "\0";
static char __pyx_k15[] = "join";
static char __pyx_k16[] = "We expect references to be tuples not: %s";
static char __pyx_k17[] = "We expect reference bits to be strings not: %s";
static char __pyx_k18[] = "Expected a plain str for value not: %s";

static PyObject *__pyx_n_join;
static PyObject *__pyx_n_parse;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;
static PyObject *__pyx_k16p;
static PyObject *__pyx_k17p;
static PyObject *__pyx_k18p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_join, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_parse, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, 0, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k16p, 0, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k17p, 0, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_k18p, 0, __pyx_k18, sizeof(__pyx_k18)},
  {0, 0, 0, 0}
};



/* Implementation of bzrlib._btree_serializer_pyx */

static void *__pyx_f_6bzrlib_21_btree_serializer_pyx__my_memrchr(void *__pyx_v_s,int __pyx_v_c,size_t __pyx_v_n) {
  char *__pyx_v_pos;
  char *__pyx_v_start;
  void *__pyx_r;
  int __pyx_1;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":63 */
  __pyx_v_start = ((char *)__pyx_v_s);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":64 */
  __pyx_v_pos = ((__pyx_v_start + __pyx_v_n) - 1);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":65 */
  while (1) {
    __pyx_1 = (__pyx_v_pos >= __pyx_v_start);
    if (!__pyx_1) break;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":66 */
    __pyx_1 = ((__pyx_v_pos[0]) == __pyx_v_c);
    if (__pyx_1) {
      __pyx_r = __pyx_v_pos;
      goto __pyx_L0;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":68 */
    __pyx_v_pos = (__pyx_v_pos - 1);
  }

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":69 */
  __pyx_r = NULL;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_safe_string_from_size(char *__pyx_v_s,Py_ssize_t __pyx_v_size) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":73 */
  __pyx_1 = (__pyx_v_size < 0);
  if (__pyx_1) {
    __pyx_2 = PyInt_FromSsize_t(__pyx_v_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((int)__pyx_v_s)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k1p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_4 = PyObject_CallObject(PyExc_AssertionError, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":77 */
  __pyx_2 = PyString_FromStringAndSize(__pyx_v_s,__pyx_v_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.safe_string_from_size");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_safe_interned_string_from_size(char *__pyx_v_s,Py_ssize_t __pyx_v_size) {
  PyObject *__pyx_v_py_str;
  PyObject *__pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_result = Py_None; Py_INCREF(Py_None);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":82 */
  __pyx_1 = (__pyx_v_size < 0);
  if (__pyx_1) {
    __pyx_2 = PyInt_FromSsize_t(__pyx_v_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((int)__pyx_v_s)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k1p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_4 = PyObject_CallObject(PyExc_AssertionError, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":86 */
  __pyx_v_py_str = PyString_FromStringAndSize(__pyx_v_s,__pyx_v_size);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":87 */
  PyString_InternInPlace((&__pyx_v_py_str));

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":88 */
  Py_INCREF(((PyObject *)__pyx_v_py_str));
  Py_DECREF(__pyx_v_result);
  __pyx_v_result = ((PyObject *)__pyx_v_py_str);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":91 */
  Py_DECREF(__pyx_v_py_str);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":92 */
  Py_INCREF(__pyx_v_result);
  __pyx_r = __pyx_v_result;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.safe_interned_string_from_size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  return __pyx_r;
}

static int __pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_bytes = 0;
  PyObject *__pyx_v_key_length = 0;
  PyObject *__pyx_v_ref_list_length = 0;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"bytes","key_length","ref_list_length",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_bytes, &__pyx_v_key_length, &__pyx_v_ref_list_length)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_bytes);
  Py_INCREF(__pyx_v_key_length);
  Py_INCREF(__pyx_v_ref_list_length);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":126 */
  Py_INCREF(__pyx_v_bytes);
  Py_DECREF(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->bytes);
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->bytes = __pyx_v_bytes;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":127 */
  __pyx_1 = PyInt_AsLong(__pyx_v_key_length); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->key_length = __pyx_1;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":128 */
  __pyx_1 = PyInt_AsLong(__pyx_v_ref_list_length); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->ref_list_length = __pyx_1;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":129 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->keys);
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->keys = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":130 */
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_cur_str = NULL;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":131 */
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_end_str = NULL;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":132 */
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_header_found = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.BTreeLeafParser.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_bytes);
  Py_DECREF(__pyx_v_key_length);
  Py_DECREF(__pyx_v_ref_list_length);
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_extract_key(struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *__pyx_v_self,char *__pyx_v_last) {
  char *__pyx_v_temp_ptr;
  int __pyx_v_loop_counter;
  PyObject *__pyx_v_key_segments;
  PyObject *__pyx_v_failure_string;
  PyObject *__pyx_v_key_element;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_key_segments = Py_None; Py_INCREF(Py_None);
  __pyx_v_failure_string = Py_None; Py_INCREF(Py_None);
  __pyx_v_key_element = Py_None; Py_INCREF(Py_None);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":143 */
  __pyx_v_loop_counter = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":144 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  Py_DECREF(__pyx_v_key_segments);
  __pyx_v_key_segments = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":145 */
  while (1) {
    __pyx_2 = (__pyx_v_loop_counter < __pyx_v_self->key_length);
    if (!__pyx_2) break;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":146 */
    __pyx_v_loop_counter = (__pyx_v_loop_counter + 1);

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":148 */
    __pyx_v_temp_ptr = ((char *)memchr(__pyx_v_self->_start,'\0',(__pyx_v_last - __pyx_v_self->_start)));

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":149 */
    __pyx_2 = (__pyx_v_temp_ptr == NULL);
    if (__pyx_2) {
      __pyx_2 = (__pyx_v_loop_counter == __pyx_v_self->key_length);
      if (__pyx_2) {
        __pyx_v_temp_ptr = __pyx_v_last;
        goto __pyx_L5;
      }
      /*else*/ {

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":155 */
        __pyx_1 = __pyx_f_6bzrlib_21_btree_serializer_pyx_safe_string_from_size(__pyx_v_self->_start,(__pyx_v_last - __pyx_v_self->_start)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
        __pyx_3 = PyObject_Repr(__pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_1 = PyNumber_Add(__pyx_k2p, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_v_failure_string);
        __pyx_v_failure_string = __pyx_1;
        __pyx_1 = 0;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":158 */
        __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
        Py_INCREF(__pyx_v_failure_string);
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_failure_string);
        __pyx_1 = PyObject_CallObject(PyExc_AssertionError, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __Pyx_Raise(__pyx_1, 0, 0);
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
      }
      __pyx_L5:;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":163 */
    __pyx_3 = __pyx_f_6bzrlib_21_btree_serializer_pyx_safe_interned_string_from_size(__pyx_v_self->_start,(__pyx_v_temp_ptr - __pyx_v_self->_start)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
    Py_DECREF(__pyx_v_key_element);
    __pyx_v_key_element = __pyx_3;
    __pyx_3 = 0;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":166 */
    __pyx_v_self->_start = (__pyx_v_temp_ptr + 1);

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":167 */
    __pyx_2 = PyList_Append(__pyx_v_key_segments,__pyx_v_key_element); if (__pyx_2 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  }

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":168 */
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
  Py_INCREF(__pyx_v_key_segments);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_key_segments);
  __pyx_3 = PyObject_CallObject(((PyObject *)(&PyTuple_Type)), __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.BTreeLeafParser.extract_key");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_key_segments);
  Py_DECREF(__pyx_v_failure_string);
  Py_DECREF(__pyx_v_key_element);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_process_line(struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *__pyx_v_self) {
  char *__pyx_v_last;
  char *__pyx_v_temp_ptr;
  char *__pyx_v_ref_ptr;
  char *__pyx_v_next_start;
  int __pyx_v_loop_counter;
  PyObject *__pyx_v_key;
  PyObject *__pyx_v_value;
  PyObject *__pyx_v_ref_lists;
  PyObject *__pyx_v_ref_list;
  PyObject *__pyx_v_node_value;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_key = Py_None; Py_INCREF(Py_None);
  __pyx_v_value = Py_None; Py_INCREF(Py_None);
  __pyx_v_ref_lists = Py_None; Py_INCREF(Py_None);
  __pyx_v_ref_list = Py_None; Py_INCREF(Py_None);
  __pyx_v_node_value = Py_None; Py_INCREF(Py_None);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":178 */
  __pyx_v_self->_start = __pyx_v_self->_cur_str;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":180 */
  __pyx_v_last = ((char *)memchr(__pyx_v_self->_start,'\n',(__pyx_v_self->_end_str - __pyx_v_self->_start)));

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":181 */
  __pyx_1 = (__pyx_v_last == NULL);
  if (__pyx_1) {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":183 */
    __pyx_v_last = __pyx_v_self->_end_str;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":184 */
    __pyx_v_self->_cur_str = __pyx_v_self->_end_str;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_v_self->_cur_str = (__pyx_v_last + 1);
  }
  __pyx_L2:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":190 */
  __pyx_1 = (__pyx_v_last == __pyx_v_self->_start);
  if (__pyx_1) {
    __pyx_r = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":193 */
  __pyx_1 = (__pyx_v_last < __pyx_v_self->_start);
  if (__pyx_1) {
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    Py_INCREF(__pyx_k3p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k3p);
    __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":196 */
  __pyx_1 = (0 == __pyx_v_self->_header_found);
  if (__pyx_1) {
    __pyx_1 = (strncmp(__pyx_k4,__pyx_v_self->_start,(__pyx_v_last - __pyx_v_self->_start)) == 0);
    if (__pyx_1) {

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":199 */
      __pyx_v_self->_header_found = 1;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":200 */
      __pyx_r = 0;
      goto __pyx_L0;
      goto __pyx_L6;
    }
    /*else*/ {
      __pyx_2 = __pyx_f_6bzrlib_21_btree_serializer_pyx_safe_string_from_size(__pyx_v_self->_start,(__pyx_v_last - __pyx_v_self->_start)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
      __pyx_3 = PyNumber_Remainder(__pyx_k5p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
      __pyx_3 = 0;
      __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    }
    __pyx_L6:;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":205 */
  __pyx_2 = ((struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self->__pyx_vtab)->extract_key(__pyx_v_self,__pyx_v_last); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
  Py_DECREF(__pyx_v_key);
  __pyx_v_key = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":207 */
  __pyx_v_temp_ptr = ((char *)__pyx_f_6bzrlib_21_btree_serializer_pyx__my_memrchr(__pyx_v_self->_start,'\0',(__pyx_v_last - __pyx_v_self->_start)));

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":208 */
  __pyx_1 = (__pyx_v_temp_ptr == NULL);
  if (__pyx_1) {
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
    Py_INCREF(__pyx_k6p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k6p);
    __pyx_2 = PyObject_CallObject(PyExc_AssertionError, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
    goto __pyx_L7;
  }
  /*else*/ {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":213 */
    __pyx_3 = __pyx_f_6bzrlib_21_btree_serializer_pyx_safe_string_from_size((__pyx_v_temp_ptr + 1),((__pyx_v_last - __pyx_v_temp_ptr) - 1)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_3;
    __pyx_3 = 0;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":215 */
    __pyx_v_last = __pyx_v_temp_ptr;
  }
  __pyx_L7:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":216 */
  __pyx_1 = __pyx_v_self->ref_list_length;
  if (__pyx_1) {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":217 */
    __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ref_lists);
    __pyx_v_ref_lists = __pyx_2;
    __pyx_2 = 0;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":218 */
    __pyx_v_loop_counter = 0;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":219 */
    while (1) {
      __pyx_1 = (__pyx_v_loop_counter < __pyx_v_self->ref_list_length);
      if (!__pyx_1) break;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":220 */
      __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      Py_DECREF(__pyx_v_ref_list);
      __pyx_v_ref_list = __pyx_3;
      __pyx_3 = 0;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":222 */
      __pyx_v_loop_counter = (__pyx_v_loop_counter + 1);

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":223 */
      __pyx_1 = (__pyx_v_last < __pyx_v_self->_start);
      if (__pyx_1) {
        __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
        Py_INCREF(__pyx_k3p);
        PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k3p);
        __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        __Pyx_Raise(__pyx_3, 0, 0);
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
        goto __pyx_L11;
      }
      __pyx_L11:;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":226 */
      __pyx_v_temp_ptr = ((char *)memchr(__pyx_v_self->_start,'\t',(__pyx_v_last - __pyx_v_self->_start)));

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":227 */
      __pyx_1 = (__pyx_v_temp_ptr == NULL);
      if (__pyx_1) {
        __pyx_1 = (__pyx_v_loop_counter != __pyx_v_self->ref_list_length);
        if (__pyx_1) {
          __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
          Py_INCREF(__pyx_k7p);
          PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k7p);
          __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
          Py_DECREF(__pyx_2); __pyx_2 = 0;
          __Pyx_Raise(__pyx_3, 0, 0);
          Py_DECREF(__pyx_3); __pyx_3 = 0;
          {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
          goto __pyx_L13;
        }
        /*else*/ {

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":235 */
          __pyx_v_ref_ptr = __pyx_v_last;

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":236 */
          __pyx_v_next_start = __pyx_v_last;
        }
        __pyx_L13:;
        goto __pyx_L12;
      }
      /*else*/ {

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":239 */
        __pyx_v_ref_ptr = __pyx_v_temp_ptr;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":240 */
        __pyx_v_next_start = (__pyx_v_temp_ptr + 1);
      }
      __pyx_L12:;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":242 */
      while (1) {
        __pyx_1 = (__pyx_v_self->_start < __pyx_v_ref_ptr);
        if (!__pyx_1) break;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":244 */
        __pyx_v_temp_ptr = ((char *)memchr(__pyx_v_self->_start,'\r',(__pyx_v_ref_ptr - __pyx_v_self->_start)));

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":246 */
        __pyx_1 = (__pyx_v_temp_ptr == NULL);
        if (__pyx_1) {
          __pyx_v_temp_ptr = __pyx_v_ref_ptr;
          goto __pyx_L16;
        }
        __pyx_L16:;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":249 */
        __pyx_2 = ((struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self->__pyx_vtab)->extract_key(__pyx_v_self,__pyx_v_temp_ptr); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
        __pyx_1 = PyList_Append(__pyx_v_ref_list,__pyx_2); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
      }

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":250 */
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
      Py_INCREF(__pyx_v_ref_list);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_ref_list);
      __pyx_2 = PyObject_CallObject(((PyObject *)(&PyTuple_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_1 = PyList_Append(__pyx_v_ref_lists,__pyx_2); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":252 */
      __pyx_v_self->_start = __pyx_v_next_start;
    }

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":253 */
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
    Py_INCREF(__pyx_v_ref_lists);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_ref_lists);
    __pyx_2 = PyObject_CallObject(((PyObject *)(&PyTuple_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_ref_lists);
    __pyx_v_ref_lists = __pyx_2;
    __pyx_2 = 0;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":254 */
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
    Py_INCREF(__pyx_v_value);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_value);
    Py_INCREF(__pyx_v_ref_lists);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_ref_lists);
    Py_DECREF(__pyx_v_node_value);
    __pyx_v_node_value = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L8;
  }
  /*else*/ {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":256 */
    __pyx_1 = (__pyx_v_last != __pyx_v_self->_start);
    if (__pyx_1) {
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 258; goto __pyx_L1;}
      Py_INCREF(__pyx_k8p);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k8p);
      __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 258; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 258; goto __pyx_L1;}
      goto __pyx_L17;
    }
    __pyx_L17:;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":259 */
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 259; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 259; goto __pyx_L1;}
    Py_INCREF(__pyx_v_value);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_value);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
    __pyx_2 = 0;
    Py_DECREF(__pyx_v_node_value);
    __pyx_v_node_value = __pyx_3;
    __pyx_3 = 0;
  }
  __pyx_L8:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":260 */
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_key);
  Py_INCREF(__pyx_v_node_value);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_node_value);
  __pyx_1 = PyList_Append(__pyx_v_self->keys,__pyx_2); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":261 */
  __pyx_r = 0;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.BTreeLeafParser.process_line");
  __pyx_r = (-1);
  __pyx_L0:;
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_ref_lists);
  Py_DECREF(__pyx_v_ref_list);
  Py_DECREF(__pyx_v_node_value);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_parse(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_parse(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  Py_ssize_t __pyx_v_byte_count;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  char *__pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":265 */
  __pyx_1 = (!PyString_CheckExact(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->bytes));
  if (__pyx_1) {
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L1;}
    Py_INCREF(__pyx_k9p);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k9p);
    __pyx_3 = PyObject_CallObject(PyExc_AssertionError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 266; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":267 */
  __pyx_v_byte_count = PyString_Size(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->bytes);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":268 */
  __pyx_4 = PyString_AsString(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->bytes); if (__pyx_4 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 268; goto __pyx_L1;}
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_cur_str = __pyx_4;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":270 */
  ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_end_str = (((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_cur_str + __pyx_v_byte_count);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":271 */
  while (1) {
    __pyx_1 = (((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_cur_str < ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->_end_str);
    if (!__pyx_1) break;
    __pyx_1 = ((struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->__pyx_vtab)->process_line(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 272; goto __pyx_L1;}
  }

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":273 */
  Py_INCREF(((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->keys);
  __pyx_r = ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)__pyx_v_self)->keys;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx.BTreeLeafParser.parse");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx__parse_leaf_lines(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx__parse_leaf_lines(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_bytes = 0;
  PyObject *__pyx_v_key_length = 0;
  PyObject *__pyx_v_ref_list_length = 0;
  PyObject *__pyx_v_parser;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"bytes","key_length","ref_list_length",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_bytes, &__pyx_v_key_length, &__pyx_v_ref_list_length)) return 0;
  Py_INCREF(__pyx_v_bytes);
  Py_INCREF(__pyx_v_key_length);
  Py_INCREF(__pyx_v_ref_list_length);
  __pyx_v_parser = Py_None; Py_INCREF(Py_None);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":277 */
  __pyx_1 = PyTuple_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  Py_INCREF(__pyx_v_bytes);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_bytes);
  Py_INCREF(__pyx_v_key_length);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_key_length);
  Py_INCREF(__pyx_v_ref_list_length);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_ref_list_length);
  __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_parser);
  __pyx_v_parser = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":278 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_parser, __pyx_n_parse); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 278; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 278; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx._parse_leaf_lines");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_parser);
  Py_DECREF(__pyx_v_bytes);
  Py_DECREF(__pyx_v_key_length);
  Py_DECREF(__pyx_v_ref_list_length);
  return __pyx_r;
}

static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx__flatten_node(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6bzrlib_21_btree_serializer_pyx__flatten_node[] = "Convert a node into the serialized form.\n\n    :param node: A tuple representing a node:\n        (index, key_tuple, value, references)\n    :param reference_lists: Does this index have reference lists?\n    :return: (string_key, flattened)\n        string_key  The serialized key for referencing this node\n        flattened   A string with the serialized form for the contents\n    ";
static PyObject *__pyx_f_6bzrlib_21_btree_serializer_pyx__flatten_node(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_node = 0;
  PyObject *__pyx_v_reference_lists = 0;
  int __pyx_v_have_reference_lists;
  Py_ssize_t __pyx_v_flat_len;
  Py_ssize_t __pyx_v_key_len;
  Py_ssize_t __pyx_v_node_len;
  PyObject *__pyx_v_val;
  char *__pyx_v_value;
  Py_ssize_t __pyx_v_value_len;
  char *__pyx_v_out;
  Py_ssize_t __pyx_v_refs_len;
  Py_ssize_t __pyx_v_next_len;
  int __pyx_v_first_ref_list;
  int __pyx_v_first_reference;
  int __pyx_v_i;
  PyObject *__pyx_v_ref_bit;
  Py_ssize_t __pyx_v_ref_bit_len;
  PyObject *__pyx_v_string_key;
  PyObject *__pyx_v_ref_lists;
  PyObject *__pyx_v_ref_list;
  PyObject *__pyx_v_reference;
  PyObject *__pyx_v_line;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_ssize_t __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  char *__pyx_7;
  static char *__pyx_argnames[] = {"node","reference_lists",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_node, &__pyx_v_reference_lists)) return 0;
  Py_INCREF(__pyx_v_node);
  Py_INCREF(__pyx_v_reference_lists);
  __pyx_v_string_key = Py_None; Py_INCREF(Py_None);
  __pyx_v_ref_lists = Py_None; Py_INCREF(Py_None);
  __pyx_v_ref_list = Py_None; Py_INCREF(Py_None);
  __pyx_v_reference = Py_None; Py_INCREF(Py_None);
  __pyx_v_line = Py_None; Py_INCREF(Py_None);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":307 */
  __pyx_1 = (!PyTuple_CheckExact(__pyx_v_node));
  if (__pyx_1) {
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 309; goto __pyx_L1;}
    Py_INCREF(__pyx_v_node);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_node);
    __pyx_3 = PyObject_CallObject(((PyObject *)(&PyType_Type)), __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 309; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k11p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 309; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_TypeError, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":310 */
  __pyx_v_node_len = PyTuple_GET_SIZE(__pyx_v_node);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":311 */
  __pyx_1 = PyInt_AsLong(__pyx_v_reference_lists); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 311; goto __pyx_L1;}
  __pyx_v_have_reference_lists = __pyx_1;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":312 */
  __pyx_1 = __pyx_v_have_reference_lists;
  if (__pyx_1) {
    __pyx_1 = (__pyx_v_node_len != 4);
    if (__pyx_1) {
      __pyx_4 = PyObject_Length(__pyx_v_node); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 315; goto __pyx_L1;}
      __pyx_3 = PyInt_FromSsize_t(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 315; goto __pyx_L1;}
      __pyx_2 = PyNumber_Remainder(__pyx_k12p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 315; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 314; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
      __pyx_2 = 0;
      __pyx_2 = PyObject_CallObject(PyExc_ValueError, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 314; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __Pyx_Raise(__pyx_2, 0, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 314; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;
    goto __pyx_L3;
  }
  __pyx_1 = (__pyx_v_node_len < 3);
  if (__pyx_1) {
    __pyx_4 = PyObject_Length(__pyx_v_node); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
    __pyx_3 = PyInt_FromSsize_t(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
    __pyx_2 = PyNumber_Remainder(__pyx_k13p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_ValueError, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":320 */
  __pyx_3 = PyObject_GetAttr(__pyx_k14p, __pyx_n_join); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 320; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 320; goto __pyx_L1;}
  Py_INCREF(((PyObject *)PyTuple_GET_ITEM(__pyx_v_node,1)));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)PyTuple_GET_ITEM(__pyx_v_node,1)));
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 320; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_string_key);
  __pyx_v_string_key = __pyx_5;
  __pyx_5 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":334 */
  __pyx_v_refs_len = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":335 */
  __pyx_1 = __pyx_v_have_reference_lists;
  if (__pyx_1) {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":337 */
    Py_INCREF(((PyObject *)PyTuple_GET_ITEM(__pyx_v_node,3)));
    Py_DECREF(__pyx_v_ref_lists);
    __pyx_v_ref_lists = ((PyObject *)PyTuple_GET_ITEM(__pyx_v_node,3));

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":338 */
    __pyx_4 = PyObject_Length(__pyx_v_ref_lists); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 338; goto __pyx_L1;}
    __pyx_v_next_len = __pyx_4;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":339 */
    __pyx_1 = (__pyx_v_next_len > 0);
    if (__pyx_1) {

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":343 */
      __pyx_v_refs_len = (__pyx_v_refs_len + (__pyx_v_next_len - 1));

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":344 */
      __pyx_3 = PyObject_GetIter(__pyx_v_ref_lists); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
      for (;;) {
        __pyx_2 = PyIter_Next(__pyx_3);
        if (!__pyx_2) {
          if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
          break;
        }
        Py_DECREF(__pyx_v_ref_list);
        __pyx_v_ref_list = __pyx_2;
        __pyx_2 = 0;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":345 */
        __pyx_4 = PyObject_Length(__pyx_v_ref_list); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 345; goto __pyx_L1;}
        __pyx_v_next_len = __pyx_4;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":346 */
        __pyx_1 = (__pyx_v_next_len > 0);
        if (__pyx_1) {

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":349 */
          __pyx_v_refs_len = (__pyx_v_refs_len + (__pyx_v_next_len - 1));

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":350 */
          __pyx_5 = PyObject_GetIter(__pyx_v_ref_list); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 350; goto __pyx_L1;}
          for (;;) {
            __pyx_2 = PyIter_Next(__pyx_5);
            if (!__pyx_2) {
              if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 350; goto __pyx_L1;}
              break;
            }
            Py_DECREF(__pyx_v_reference);
            __pyx_v_reference = __pyx_2;
            __pyx_2 = 0;

            /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":351 */
            __pyx_1 = (!PyTuple_CheckExact(__pyx_v_reference));
            if (__pyx_1) {
              __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
              Py_INCREF(__pyx_v_reference);
              PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_reference);
              __pyx_6 = PyObject_CallObject(((PyObject *)(&PyType_Type)), __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
              Py_DECREF(__pyx_2); __pyx_2 = 0;
              __pyx_2 = PyNumber_Remainder(__pyx_k16p, __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
              Py_DECREF(__pyx_6); __pyx_6 = 0;
              __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 352; goto __pyx_L1;}
              PyTuple_SET_ITEM(__pyx_6, 0, __pyx_2);
              __pyx_2 = 0;
              __pyx_2 = PyObject_CallObject(PyExc_TypeError, __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 352; goto __pyx_L1;}
              Py_DECREF(__pyx_6); __pyx_6 = 0;
              __Pyx_Raise(__pyx_2, 0, 0);
              Py_DECREF(__pyx_2); __pyx_2 = 0;
              {__pyx_filename = __pyx_f[0]; __pyx_lineno = 352; goto __pyx_L1;}
              goto __pyx_L12;
            }
            __pyx_L12:;

            /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":355 */
            __pyx_v_next_len = PyTuple_GET_SIZE(__pyx_v_reference);

            /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":356 */
            __pyx_1 = (__pyx_v_next_len > 0);
            if (__pyx_1) {

              /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":359 */
              __pyx_v_refs_len = (__pyx_v_refs_len + (__pyx_v_next_len - 1));

              /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":360 */
              for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_next_len; ++__pyx_v_i) {

                /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":361 */
                __pyx_v_ref_bit = PyTuple_GET_ITEM(__pyx_v_reference,__pyx_v_i);

                /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":362 */
                __pyx_1 = (!PyString_CheckExact(__pyx_v_ref_bit));
                if (__pyx_1) {
                  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 365; goto __pyx_L1;}
                  Py_INCREF(((PyObject *)__pyx_v_ref_bit));
                  PyTuple_SET_ITEM(__pyx_6, 0, ((PyObject *)__pyx_v_ref_bit));
                  __pyx_2 = PyObject_CallObject(((PyObject *)(&PyType_Type)), __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 365; goto __pyx_L1;}
                  Py_DECREF(__pyx_6); __pyx_6 = 0;
                  __pyx_6 = PyNumber_Remainder(__pyx_k17p, __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 365; goto __pyx_L1;}
                  Py_DECREF(__pyx_2); __pyx_2 = 0;
                  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 363; goto __pyx_L1;}
                  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_6);
                  __pyx_6 = 0;
                  __pyx_6 = PyObject_CallObject(PyExc_TypeError, __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 363; goto __pyx_L1;}
                  Py_DECREF(__pyx_2); __pyx_2 = 0;
                  __Pyx_Raise(__pyx_6, 0, 0);
                  Py_DECREF(__pyx_6); __pyx_6 = 0;
                  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 363; goto __pyx_L1;}
                  goto __pyx_L16;
                }
                __pyx_L16:;

                /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":366 */
                __pyx_v_refs_len = (__pyx_v_refs_len + PyString_GET_SIZE(__pyx_v_ref_bit));
              }
              goto __pyx_L13;
            }
            __pyx_L13:;
          }
          Py_DECREF(__pyx_5); __pyx_5 = 0;
          goto __pyx_L9;
        }
        __pyx_L9:;
      }
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":369 */
  __pyx_v_key_len = PyString_Size(__pyx_v_string_key);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":370 */
  __pyx_v_val = PyTuple_GET_ITEM(__pyx_v_node,2);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":371 */
  __pyx_1 = (!PyString_CheckExact(__pyx_v_val));
  if (__pyx_1) {
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 373; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_val));
    PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_val));
    __pyx_6 = PyObject_CallObject(((PyObject *)(&PyType_Type)), __pyx_2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 373; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyNumber_Remainder(__pyx_k18p, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 373; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 372; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_TypeError, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 372; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 372; goto __pyx_L1;}
    goto __pyx_L17;
  }
  __pyx_L17:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":374 */
  __pyx_v_value = PyString_AS_STRING(__pyx_v_val);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":375 */
  __pyx_v_value_len = PyString_GET_SIZE(__pyx_v_val);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":376 */
  __pyx_v_flat_len = (((((__pyx_v_key_len + 1) + __pyx_v_refs_len) + 1) + __pyx_v_value_len) + 1);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":377 */
  __pyx_6 = PyString_FromStringAndSize(NULL,__pyx_v_flat_len); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 377; goto __pyx_L1;}
  Py_DECREF(__pyx_v_line);
  __pyx_v_line = __pyx_6;
  __pyx_6 = 0;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":379 */
  __pyx_7 = PyString_AsString(__pyx_v_line); if (__pyx_7 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 379; goto __pyx_L1;}
  __pyx_v_out = __pyx_7;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":380 */
  __pyx_7 = PyString_AsString(__pyx_v_string_key); if (__pyx_7 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 380; goto __pyx_L1;}
  memcpy(__pyx_v_out,__pyx_7,__pyx_v_key_len);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":381 */
  __pyx_v_out = (__pyx_v_out + __pyx_v_key_len);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":382 */
  (__pyx_v_out[0]) = '\0';

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":383 */
  __pyx_v_out = (__pyx_v_out + 1);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":384 */
  __pyx_1 = (__pyx_v_refs_len > 0);
  if (__pyx_1) {

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":385 */
    __pyx_v_first_ref_list = 1;

    /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":386 */
    __pyx_5 = PyObject_GetIter(__pyx_v_ref_lists); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 386; goto __pyx_L1;}
    for (;;) {
      __pyx_3 = PyIter_Next(__pyx_5);
      if (!__pyx_3) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 386; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_ref_list);
      __pyx_v_ref_list = __pyx_3;
      __pyx_3 = 0;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":387 */
      __pyx_1 = (__pyx_v_first_ref_list == 0);
      if (__pyx_1) {

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":388 */
        (__pyx_v_out[0]) = '\t';

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":389 */
        __pyx_v_out = (__pyx_v_out + 1);
        goto __pyx_L21;
      }
      __pyx_L21:;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":390 */
      __pyx_v_first_ref_list = 0;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":391 */
      __pyx_v_first_reference = 1;

      /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":392 */
      __pyx_2 = PyObject_GetIter(__pyx_v_ref_list); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 392; goto __pyx_L1;}
      for (;;) {
        __pyx_6 = PyIter_Next(__pyx_2);
        if (!__pyx_6) {
          if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 392; goto __pyx_L1;}
          break;
        }
        Py_DECREF(__pyx_v_reference);
        __pyx_v_reference = __pyx_6;
        __pyx_6 = 0;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":393 */
        __pyx_1 = (__pyx_v_first_reference == 0);
        if (__pyx_1) {

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":394 */
          (__pyx_v_out[0]) = '\r';

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":395 */
          __pyx_v_out = (__pyx_v_out + 1);
          goto __pyx_L24;
        }
        __pyx_L24:;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":396 */
        __pyx_v_first_reference = 0;

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":397 */
        __pyx_v_next_len = PyTuple_GET_SIZE(__pyx_v_reference);

        /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":398 */
        for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_next_len; ++__pyx_v_i) {

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":399 */
          __pyx_1 = (__pyx_v_i != 0);
          if (__pyx_1) {

            /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":400 */
            (__pyx_v_out[0]) = '\x000';

            /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":401 */
            __pyx_v_out = (__pyx_v_out + 1);
            goto __pyx_L27;
          }
          __pyx_L27:;

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":402 */
          __pyx_v_ref_bit = PyTuple_GET_ITEM(__pyx_v_reference,__pyx_v_i);

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":403 */
          __pyx_v_ref_bit_len = PyString_GET_SIZE(__pyx_v_ref_bit);

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":404 */
          memcpy(__pyx_v_out,PyString_AS_STRING(__pyx_v_ref_bit),__pyx_v_ref_bit_len);

          /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":405 */
          __pyx_v_out = (__pyx_v_out + __pyx_v_ref_bit_len);
        }
      }
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L18;
  }
  __pyx_L18:;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":406 */
  (__pyx_v_out[0]) = '\0';

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":407 */
  __pyx_v_out = (__pyx_v_out + 1);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":408 */
  memcpy(__pyx_v_out,__pyx_v_value,__pyx_v_value_len);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":409 */
  __pyx_v_out = (__pyx_v_out + __pyx_v_value_len);

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":410 */
  (__pyx_v_out[0]) = '\n';

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":411 */
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 411; goto __pyx_L1;}
  Py_INCREF(__pyx_v_string_key);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_string_key);
  Py_INCREF(__pyx_v_line);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_line);
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx._flatten_node");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_string_key);
  Py_DECREF(__pyx_v_ref_lists);
  Py_DECREF(__pyx_v_ref_list);
  Py_DECREF(__pyx_v_reference);
  Py_DECREF(__pyx_v_line);
  Py_DECREF(__pyx_v_node);
  Py_DECREF(__pyx_v_reference_lists);
  return __pyx_r;
}
static struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser __pyx_vtable_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser;

static PyObject *__pyx_tp_new_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)o);
  *(struct __pyx_vtabstruct_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser **)&p->__pyx_vtab = __pyx_vtabptr_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser;
  p->bytes = Py_None; Py_INCREF(Py_None);
  p->keys = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser(PyObject *o) {
  struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *p = (struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)o;
  Py_XDECREF(p->bytes);
  Py_XDECREF(p->keys);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *p = (struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)o;
  if (p->bytes) {
    e = (*v)(p->bytes, a); if (e) return e;
  }
  if (p->keys) {
    e = (*v)(p->keys, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser(PyObject *o) {
  struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *p = (struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser *)o;
  PyObject *t;
  t = p->bytes; 
  p->bytes = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->keys; 
  p->keys = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser[] = {
  {"parse", (PyCFunction)__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_parse, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BTreeLeafParser = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_BTreeLeafParser = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BTreeLeafParser = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BTreeLeafParser = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "bzrlib._btree_serializer_pyx.BTreeLeafParser", /*tp_name*/
  sizeof(struct __pyx_obj_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BTreeLeafParser, /*tp_as_number*/
  &__pyx_tp_as_sequence_BTreeLeafParser, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BTreeLeafParser, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BTreeLeafParser, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "Parse the leaf nodes of a BTree index.\n\n    :ivar bytes: The PyString object containing the uncompressed text for the\n        node.\n    :ivar key_length: An integer describing how many pieces the keys have for\n        this index.\n    :ivar ref_list_length: An integer describing how many references this index\n        contains.\n    :ivar keys: A PyList of keys found in this node.\n\n    :ivar _cur_str: A pointer to the start of the next line to parse\n    :ivar _end_str: A pointer to the end of bytes\n    :ivar _start: Pointer to the location within the current line while\n        parsing.\n    :ivar _header_found: True when we have parsed the header for this node\n    ", /*tp_doc*/
  __pyx_tp_traverse_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser, /*tp_traverse*/
  __pyx_tp_clear_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"_parse_leaf_lines", (PyCFunction)__pyx_f_6bzrlib_21_btree_serializer_pyx__parse_leaf_lines, METH_VARARGS|METH_KEYWORDS, 0},
  {"_flatten_node", (PyCFunction)__pyx_f_6bzrlib_21_btree_serializer_pyx__flatten_node, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6bzrlib_21_btree_serializer_pyx__flatten_node},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_btree_serializer_pyx(void); /*proto*/
PyMODINIT_FUNC init_btree_serializer_pyx(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_btree_serializer_pyx", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;};
  __pyx_vtabptr_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser = &__pyx_vtable_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser;
  *(void(**)(void))&__pyx_vtable_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser.extract_key = (void(*)(void))__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_extract_key;
  *(void(**)(void))&__pyx_vtable_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser.process_line = (void(*)(void))__pyx_f_6bzrlib_21_btree_serializer_pyx_15BTreeLeafParser_process_line;
  __pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser.tp_dict, __pyx_vtabptr_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BTreeLeafParser", (PyObject *)&__pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_ptype_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser = &__pyx_type_6bzrlib_21_btree_serializer_pyx_BTreeLeafParser;

  /* "/home/jameinel/dev/bzr/work/bzrlib/_btree_serializer_pyx.pyx":281 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("bzrlib._btree_serializer_pyx");
}

static char *__pyx_filenames[] = {
  "_btree_serializer_pyx.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
